### PR TITLE
Fix TestFailedException outcome not propagating to TestResult outcome

### LINKED ISSUE #5226: MSTest - ClassInitialize - Assert.Inconclusive fails the workflow on MSTest 3.8.2, but not on 3.7.3
## Describe the bug

After upgrading MSTest from 3.7.3 to 3.8.2, unit tests start failing. Inside the ClassInitialize, we use the Assert.Inconclusive() if a certain environment variable / user secret is not present (cause not everything can necessarily run on GitHub). This was working nicely, but after updating MSTest to 3.8.2, this started failing the unit tests instead of marking them as skipped like before.

## Steps To Reproduce

See the following workflow run: [https://github.com/MichielOda/MSTestClassInitializeInconclusive/actions/runs/13831330210](https://github.com/MichielOda/MSTestClassInitializeInconclusive/actions/runs/13831330210)

## Expected behavior
After changing to MSTest 3.8.2, the tests keep on working like normal.

## Actual behavior
The Inconclusive in the ClassInitialize is failing the tests instead of marking them as skipped.

## Additional context

Full test repo: [https://github.com/MichielOda/MSTestClassInitializeInconclusive](https://github.com/MichielOda/MSTestClassInitializeInconclusive)

I went over the changes of the 3.8.x range, but didn't saw something immediately that could be the cause of this issue. Of course, I could have missed it due to terminology that I'm missing.

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #5226

Looks like it could be a regression from #4686

### CODE REVIEW

File: test/IntegrationTests/MSTest.Acceptance.IntegrationTests/InconclusiveTests.cs [hunk 1]
```diff
@@ -0,0 +1,235 @@
...
+
+    [TestMethod]
+    [DataRow(Lifecycle.AssemblyInitialize)]
+    [DataRow(Lifecycle.ClassInitialize)]
+    [DataRow(Lifecycle.TestInitialize)]
+    [DataRow(Lifecycle.TestMethod)]
+    [DataRow(Lifecycle.TestCleanup)]
+    [DataRow(Lifecycle.ClassCleanup)]
+    [DataRow(Lifecycle.AssemblyCleanup)]
+    public async Task TestOutcomeShouldBeRespectedCorrectly(Lifecycle inconclusiveStep)
```
Comment (Evangelink) [inline test/IntegrationTests/MSTest.Acceptance.IntegrationTests/InconclusiveTests.cs:32]: It'd be nice to have the "values source" attribute for such case

Comment (Evangelink) [inline test/IntegrationTests/MSTest.Acceptance.IntegrationTests/InconclusiveTests.cs:32]: Fine as-is but I am wondering if a different test for each case would not be clearer for people reviewing in the future.

File: test/UnitTests/MSTestAdapter.UnitTests/Execution/TestClassInfoTests.cs [hunk 2]
```diff
@@ -207,7 +207,7 @@ public void RunClassInitializeShouldThrowIfTestContextIsNull()
         TestResult result = GetResultOrRunClassInitialize(null);
         var exception = result.TestFailureException as TestFailedException;
         Verify(exception is not null);
-        Verify(result.Outcome == UTF.UnitTestOutcome.Failed);
+        Verify(result.Outcome == UTF.UnitTestOutcome.Error);
```
Comment (Evangelink) [inline test/UnitTests/MSTestAdapter.UnitTests/Execution/TestClassInfoTests.cs:210]: It's hard to understand if the change here makes sense or not so I'll approve but please have a quick look.

**Review by Evangelink — APPROVED** [review]

File: test/UnitTests/MSTestAdapter.UnitTests/Execution/TestClassInfoTests.cs (hunk 2 above)
Comment (Youssef1313) [reply test/UnitTests/MSTestAdapter.UnitTests/Execution/TestClassInfoTests.cs:210]: The unit test passes `null` as TestContext which is something that never happens in production actually. Even if it happens, I think `Error` makes better sense as it's more of MSTest error rather than a "failing" test on user side.

File: test/IntegrationTests/MSTest.Acceptance.IntegrationTests/InconclusiveTests.cs (hunk 1 above)
Comment (Youssef1313) [reply test/IntegrationTests/MSTest.Acceptance.IntegrationTests/InconclusiveTests.cs:32]: I'll merge as we discussed.

Comment (Youssef1313) [reply test/IntegrationTests/MSTest.Acceptance.IntegrationTests/InconclusiveTests.cs:32]: I'll merge as we discussed.
