### PR TITLE
Fix regressions with DataRow supported arguments

### LINKED ISSUE #1445: Regression in MSTest v3 DataRow
## Describe the bug

The example below was working up to MSTest v3 and now is raising some compiler warning `CS0182: An attribute argument must be a constant expression, typeof expression or array creation expression of an attribute parameter type`.

## Steps To Reproduce

```csharp
[TestMethod]
[DataRow(new string[] { "" })] // Compiler warning
public void StringArray(string[] lines)
{
}
```

[AB#1697642](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1697642)

### PR DESCRIPTION
**Pull request by Evangelink**
Fixes #1445

### CODE REVIEW

File: src/TestFramework/TestFramework/Attributes/DataSource/DataRowAttribute.cs [hunk 1]
```diff
@@ -15,25 +15,279 @@ namespace Microsoft.VisualStudio.TestTools.UnitTesting;
 [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
 public class DataRowAttribute : Attribute, ITestDataSource
 {
+    /// <summary>
+    /// Initializes a new instance of the <see cref="DataRowAttribute"/> class.
+    /// </summary>
+    public DataRowAttribute()
```
Comment (Evangelink) [inline src/TestFramework/TestFramework/Attributes/DataSource/DataRowAttribute.cs:21]: IMO we should **not** keep this one because that's equivalent to not having any data (we expect parameterless method). WDYT?

**Review by jakubch1 — DISMISSED** [review]

File: src/TestFramework/TestFramework/Attributes/DataSource/DataRowAttribute.cs (hunk 1 above)
Comment (jakubch1) [reply src/TestFramework/TestFramework/Attributes/DataSource/DataRowAttribute.cs:21]: Are you confident enough that this will not break people?

Comment (Evangelink) [reply src/TestFramework/TestFramework/Attributes/DataSource/DataRowAttribute.cs:21]: If they were using this case, it would break them for sure but the case makes no functional sense.

I mean if you write:

```csharp
[TestMethod]
[DataRow()]
public void A() {}
```

Why not simply doing:

```csharp
[TestMethod]
public void A() {}
```

Comment (jakubch1) [reply src/TestFramework/TestFramework/Attributes/DataSource/DataRowAttribute.cs:21]: Any such case in github?

Comment (Evangelink) [reply src/TestFramework/TestFramework/Attributes/DataSource/DataRowAttribute.cs:21]: Looking at GH, it seems that some people are using it (mainly us but also some others):
https://grep.app/search?q=%5BDataRow%28%29%5D

Comment (Evangelink) [reply src/TestFramework/TestFramework/Attributes/DataSource/DataRowAttribute.cs:21]: Otherwise we keep and mark as `Obsolete` so we can remove in v4. Sounds like best course of action.

**Review by jakubch1 — APPROVED** [review]

**Review by MarcoRossignoli — APPROVED** [review]
