### PR TITLE
Fix class/assembly cleanups log collect and attachment

### LINKED ISSUE #1448: Trace.WriteLine in AssemblyCleanup is not printed in MSTest v3.0.0
## Describe the bug

Methods having the **AssemblyCleanupAttribute** are not called.

Example:
```
[TestClass]
public sealed class DummyUnitTest
{
    [AssemblyInitialize]
    public static void AssemblyInit(TestContext testContext)
    {
        Trace.WriteLine(nameof(AssemblyInit));
    }

    [AssemblyCleanup]
    public static void AssemblblyCleanup()
    {
        Trace.WriteLine(nameof(AssemblblyCleanup));
    }

    [TestMethod]
    public void DummyTest()
    {
        Trace.WriteLine(nameof(this.DummyTest));
    }
}
```

Expected output (by MSTest 2.2.10):
```
...
AssemblyInit
DummyTest
AssemblblyCleanup
...
```

Actual output (by MSTest 3.0.0)
```
...
AssemblyInit
DummyTest
...
```

## Steps To Reproduce

Run the unit test as described above with MSTest v3.0.0.

## Expected behavior

The AssemblblyCleanup method should be called.

## Actual behavior

The AssemblblyCleanup method is not called.

[AB#1699540](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1699540)

### PR DESCRIPTION
**Pull request by Evangelink**
- Ensures Trace/Debug/Console logs calls inside `ClassCleanup `and `AssemblyCleanup `methods are correctly collected.
- Ensures that failed `ClassCleanup `or `AssemblyCleanup` is attached to last test run

Fixes #1448

### CODE REVIEW

File: src/Adapter/MSTest.TestAdapter/Execution/TestAssemblyInfo.cs [hunk 1]
```diff
@@ -234,4 +234,58 @@ public void RunAssemblyInitialize(TestContext testContext)
...
     }
+
+    /// <summary>
+    /// Calls the assembly cleanup method in a thread-safe.
+    /// </summary>
+    /// <remarks>
+    /// It is a replacement for RunAssemblyCleanup but as we are in a bug-fix version, we do not want to touch
+    /// public API and so we introduced this method.
+    /// </remarks>
+    internal void ExecuteAssemblyCleanup()
```
Comment (Evangelink) [inline src/Adapter/MSTest.TestAdapter/Execution/TestAssemblyInfo.cs:245]: Duplicates of the method above expect that we throw instead of returning string message.

File: src/Adapter/MSTest.TestAdapter/Execution/TestClassInfo.cs [hunk 2]
```diff
@@ -410,4 +410,74 @@ public void RunClassInitialize(TestContext testContext)
...
     }
+
+    /// <summary>
+    /// Execute current and base class cleanups.
+    /// </summary>
+    /// <remarks>
+    /// This is a replacement for RunClassCleanup but as we are on a bug fix version, we do not want to change
+    /// the public API, hence this method.
+    /// </remarks>
+    internal void ExecuteClassCleanup()
```
Comment (Evangelink) [inline src/Adapter/MSTest.TestAdapter/Execution/TestClassInfo.cs:421]: Duplicates of the method above except that we throw exception instead of either throwing or returning error message.

File: src/Adapter/MSTest.TestAdapter/Execution/TestAssemblyInfo.cs [hunk 3]
```diff
@@ -234,4 +234,58 @@ public void RunAssemblyInitialize(TestContext testContext)
...
+    {
+        if (AssemblyCleanupMethod == null)
```
Comment (MarcoRossignoli) [inline src/Adapter/MSTest.TestAdapter/Execution/TestAssemblyInfo.cs:247]:
```suggestion
        if (AssemblyCleanupMethod is null)
```

Comment (MarcoRossignoli) [inline src/Adapter/MSTest.TestAdapter/Execution/TestAssemblyInfo.cs:247]: should you double check inside the lock?

**Review by MarcoRossignoli — APPROVED** [review]
a comment but lgtm

File: src/Adapter/MSTest.TestAdapter/Execution/TestAssemblyInfo.cs (hunk 3 above)
Comment (MarcoRossignoli) [reply src/Adapter/MSTest.TestAdapter/Execution/TestAssemblyInfo.cs:247]: I see it's not the style....

Comment (Evangelink) [reply src/Adapter/MSTest.TestAdapter/Execution/TestAssemblyInfo.cs:247]: I will keep as-is as I am only duplicating the existing method but I will keep a note to try to improve concurrency on these classes.
