### PR TITLE
Workaround issue with managed type name utility

### LINKED ISSUE #1865: MSTest 3.x.x fails in execution with whitespace in type name
I wanted to upgrade from 2.1.2 to current MSTest.TestAdapter and MSTest.TestFramework v3.1.1, the following code will crash the test execution:

```fsharp
namespace TestiTest

open Microsoft.VisualStudio.TestTools.UnitTesting

[<TestClass>]
type ``This is a test type`` () =

    [<TestMethod>]
    member _.``This is a test`` () =
        Assert.IsTrue(true);
```
The output of that code is following:
```
Building Test Projects
========== Starting test run ==========
An exception occurred while invoking executor 'executor://mstestadapter/v2': Object reference not set to an instance of an object.
Stack trace:
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.UnitTestRunner.ClassCleanupManager.MarkTestComplete(TestMethodInfo testMethodInfo, TestMethod testMethod, Boolean& shouldRunEndOfClassCleanup, Boolean& shouldRunEndOfAssemblyCleanup) in /_/src/Adapter/MSTest.TestAdapter/Execution/UnitTestRunner.cs:line 315
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.UnitTestRunner.RunRequiredCleanups(ITestContext testContext, TestMethodInfo testMethodInfo, TestMethod testMethod, UnitTestResult[] results) in /_/src/Adapter/MSTest.TestAdapter/Execution/UnitTestRunner.cs:line 167
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.UnitTestRunner.RunSingleTest(TestMethod testMethod, IDictionary`2 testContextProperties) in /_/src/Adapter/MSTest.TestAdapter/Execution/UnitTestRunner.cs:line 145
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.TestExecutionManager.ExecuteTestsWithTestRunner(IEnumerable`1 tests, ITestExecutionRecorder testExecutionRecorder, String source, IDictionary`2 sourceLevelParameters, UnitTestRunner testRunner) in /_/src/Adapter/MSTest.TestAdapter/Execution/TestExecutionManager.cs:line 400
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.TestExecutionManager.ExecuteTestsInSource(IEnumerable`1 tests, IRunContext runContext, IFrameworkHandle frameworkHandle, String source, Boolean isDeploymentDone) in /_/src/Adapter/MSTest.TestAdapter/Execution/TestExecutionManager.cs:line 352
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.TestExecutionManager.ExecuteTests(IEnumerable`1 tests, IRunContext runContext, IFrameworkHandle frameworkHandle, Boolean isDeploymentDone) in /_/src/Adapter/MSTest.TestAdapter/Execution/TestExecutionManager.cs:line 155
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.TestExecutionManager.RunTests(IEnumerable`1 tests, IRunContext runContext, IFrameworkHandle frameworkHandle, TestRunCancellationToken runCancellationToken) in /_/src/Adapter/MSTest.TestAdapter/Execution/TestExecutionManager.cs:line 92
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.MSTestExecutor.RunTests(IEnumerable`1 tests, IRunContext runContext, IFrameworkHandle frameworkHandle) in /_/src/Adapter/MSTest.TestAdapter/MSTestExecutor.cs:line 72
   at Microsoft.VisualStudio.TestPlatform.Common.ExtensionDecorators.SerialTestRunDecorator.RunTests(IEnumerable`1 tests, IRunContext runContext, IFrameworkHandle frameworkHandle) in /_/src/Microsoft.TestPlatform.Common/ExtensionDecorators/SerialTestRunDecorator.cs:line 44
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.RunTestsWithTests.InvokeExecutor(LazyExtension`2 executor, Tuple`2 executorUri, RunContext runContext, IFrameworkHandle frameworkHandle) in /_/src/Microsoft.TestPlatform.CrossPlatEngine/Execution/RunTestsWithTests.cs:line 72
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.BaseRunTests.RunTestInternalWithExecutors(IEnumerable`1 executorUriExtensionMap, Int64 totalTests) in /_/src/Microsoft.TestPlatform.CrossPlatEngine/Execution/BaseRunTests.cs:line 466

========== Test run finished: 0 Tests (0 Passed, 0 Failed, 0 Skipped) run in 63 ms ==========
```

Visual Studio 17.8.2
`dotnet --info`:
```
.NET SDK:
 Version:           8.0.100
 Commit:            57efcf1350
 Workload version:  8.0.100-manifests.8d38d0cc

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100\
```

## Steps To Reproduce
Just execute the F# code above with 
MSTest.TestAdapter & MSTest.TestFramework both version 3.1.1 
Microsoft.NET.Test.Sdk version 17.8.0

## Additional context
Changing the code: `type ``This is a test type`` () =` to: `type ``ThisIsATest`` () =` will fix the code.
Probably are whitespaces not allowed here but in F# it's a valid type name.
I found this related issue: https://github.com/microsoft/testfx/issues/941

[AB#1925775](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1925775)

### PR DESCRIPTION
**Pull request by Evangelink**
Fixes issue #1865

### CODE REVIEW

File: src/Adapter/MSTest.TestAdapter/Execution/TypeCache.cs [hunk 1]
```diff
@@ -169,6 +181,50 @@ public override object InitializeLifetimeService()
         return classInfo;
     }
 
+    private static bool TryGetUnescapedManagedTypeName(TestMethod testMethod, [NotNullWhen(true)] out string? unescapedTypeName)
```
Comment (MarcoRossignoli) [inline src/Adapter/MSTest.TestAdapter/Execution/TypeCache.cs:184]: ❤️

**Review by MarcoRossignoli — APPROVED** [review]
