### PR TITLE
Fix MSTEST0002 codefix to not change modifier order

### LINKED ISSUE #6468: Fix for mstest0002 ignores formatting and swaps modifiers
## Describe the bug
```csharp
namespace NonPublicClass
{
    [TestClass]
    internal sealed class Test1
    {
        [TestMethod]
        public void TestMethod1()
        {
        }

        [TestMethod]
        public void TestMethod2()
        {
        }

        [TestMethod]
        public void TestMethod3()
        {
        }
    }
}
```
class warns on 0002 that is should have correct shape, but the fix looks like this:

Image

which fixes the problem, but makes to code incorrectly formatted and the modifiers are swapped.

version 3.10.3 of mstest.

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #6468

### CODE REVIEW

File: test/UnitTests/MSTest.Analyzers.UnitTests/TestClassShouldBeValidAnalyzerTests.cs [hunk 1]
```diff
@@ -214,7 +215,7 @@ private class {|#0:MyTestClass|}
             public class A
             {
                 [TestClass]
-                internal class MyTestClass
+                public class MyTestClass
```
Comment (Evangelink) [inline test/UnitTests/MSTest.Analyzers.UnitTests/TestClassShouldBeValidAnalyzerTests.cs:218]: Could we extract the change of behavior to a different PR as the target here is to fix the accessibility issue not to change the scope of the rule.

I'm thinking that if I have my full test suite setup with internal, it all works well and I apply the code fix on sln level because of just 1 hit and now it changes the full test suite I could be upset.

It might be worth adding some configuration for that, wdyt?

**Review by Evangelink — COMMENTED** [review]
LGTM - 1 nitpick but fine if you merge as-is.

File: test/UnitTests/MSTest.Analyzers.UnitTests/TestClassShouldBeValidAnalyzerTests.cs (hunk 1 above)
Comment (Youssef1313) [reply test/UnitTests/MSTest.Analyzers.UnitTests/TestClassShouldBeValidAnalyzerTests.cs:218]: > I'm thinking that if I have my full test suite setup with internal, it all works well and I apply the code fix on sln level because of just 1 hit and now it changes the full test suite I could be upset.

It's not going to change all your codebase to `internal`. Only if the accessibility was completely incorrect (originally it's nested private class in this case), we change it to public.

Comment (Evangelink) [reply test/UnitTests/MSTest.Analyzers.UnitTests/TestClassShouldBeValidAnalyzerTests.cs:218]: Oh right I am dumb it only applies to flagged instances. Approving.
