### PR TITLE
Fix FP with proper assert analyzer and IComparable

### LINKED ISSUE #7343: Possible false positive for proper assert method analyzer
When detecting `Assert.IsTrue(expr > expr2)` and suggest using `Assert.IsGreaterThan` and similar APIs, we should probably verify that the types implement `IComparable` before suggesting the fix. We also need to add test for nullable value types (e.g, `TimeSpan?`)

### PR DESCRIPTION
**Pull request by Evangelink**
Fix #7343

### CODE REVIEW

File: src/Analyzers/MSTest.Analyzers/UseProperAssertMethodsAnalyzer.cs [hunk 1]
```diff
@@ -568,6 +574,28 @@ private static ComparisonCheckStatus RecognizeComparisonCheck(
...
+        => ImplementsIComparableOfSelf(compilation, candidateType)
+            && compilation.ClassifyCommonConversion(leftType, candidateType) is { Exists: true, IsImplicit: true }
+            && compilation.ClassifyCommonConversion(rightType, candidateType) is { Exists: true, IsImplicit: true };
+
+    private static bool ImplementsIComparableOfSelf(Compilation compilation, ITypeSymbol type)
+    {
+        if (compilation.GetTypeByMetadataName("System.IComparable`1") is not INamedTypeSymbol iComparableOfT)
+        {
+            return false;
+        }
```
Comment (Youssef1313) [inline src/Analyzers/MSTest.Analyzers/UseProperAssertMethodsAnalyzer.cs]: This should be retrieved in compilation start and then get passed down.

File: src/Analyzers/MSTest.Analyzers/UseProperAssertMethodsAnalyzer.cs [hunk 2]
```diff
@@ -553,6 +554,11 @@ private static ComparisonCheckStatus RecognizeComparisonCheck(
                 return ComparisonCheckStatus.Unknown;
             }
 
+            if (!CanUseTypesWithComparableAsserts(compilation, binaryOperation.LeftOperand.Type, binaryOperation.RightOperand.Type))
```
Comment (Youssef1313) [inline src/Analyzers/MSTest.Analyzers/UseProperAssertMethodsAnalyzer.cs]: We probably need to check that the type of left operand is the same as the type of right operand, and that the type is `IComparable<T>` where `T` is the type in question. We don't need  `ClassifyCommonConversion`, most likely.

File: src/Analyzers/MSTest.Analyzers/UseProperAssertMethodsAnalyzer.cs [hunk 3]
```diff
@@ -553,6 +554,11 @@ private static ComparisonCheckStatus RecognizeComparisonCheck(
...
+            {
+                return ComparisonCheckStatus.Unknown;
```
Comment (Youssef1313) [inline src/Analyzers/MSTest.Analyzers/UseProperAssertMethodsAnalyzer.cs]: Also the logic above that special cases Enum might no longer be needed as the new code path will likely handle enums correctly.
