### PR TITLE
Datarow tests - support methods with optional parameters

### LINKED ISSUE #252: DataRow does not work with optional arguments
## Description
`DataRow` does not support for methods with optional arguments.

`TestCase` got it in https://github.com/nunit/nunit/pull/457
`Theory` got it in https://github.com/xunit/xunit/pull/997

## Steps to reproduce
```csharp
[TestMethod]
[DataRow(42)]
public void MyTestMethod(int number, string message = "")
{
    ...
}
```

## Expected behavior
Test should execute

## Actual behavior
Test fails with:
```csharp
System.Reflection.TargetParameterCountException: Parameter count mismatch.
```

### PR DESCRIPTION
**Pull request by ssa3512**
Resolves #252

### CODE REVIEW

File: src/Adapter/MSTest.CoreAdapter/Execution/TestMethodInfo.cs [hunk 1]
```diff
@@ -171,7 +171,48 @@ public virtual TestResult Invoke(object[] arguments)
...
+                    requiredParameterCount++;
+                }
+            }
+
+            if (requiredParameterCount == parameterInfos.Length)
+            {
+                return arguments;
+            }
+
+            if (arguments == null)
```
Comment (jayaranigarg) [inline src/Adapter/MSTest.CoreAdapter/Execution/TestMethodInfo.cs]: Should we just add this check to SetArguments() function itself and call ResolveArguments() only when `arguments` is not null?

File: src/Adapter/MSTest.CoreAdapter/Execution/TestMethodInfo.cs [hunk 2]
```diff
@@ -171,7 +171,48 @@ public virtual TestResult Invoke(object[] arguments)
...
+            {
+                return null;
+            }
+
+            if (arguments.Length < requiredParameterCount || arguments.Length > parameterInfos.Length)
```
Comment (jayaranigarg) [inline src/Adapter/MSTest.CoreAdapter/Execution/TestMethodInfo.cs]: Please add explanatory comments wherever possible.

File: src/Adapter/MSTest.CoreAdapter/Execution/TestMethodInfo.cs [hunk 3]
```diff
@@ -171,7 +171,48 @@ public virtual TestResult Invoke(object[] arguments)
 
         internal void SetArguments(object[] arguments)
         {
-            this.arguments = arguments;
+            this.arguments = this.ResolveArguments(arguments);
+        }
+
+        internal object[] ResolveArguments(object[] arguments)
```
Comment (jayaranigarg) [inline src/Adapter/MSTest.CoreAdapter/Execution/TestMethodInfo.cs:184]: Please add UnitTests for this function.

File: test/E2ETests/Smoke.E2E.Tests/DataRowTests.cs [hunk 4]
```diff
@@ -21,12 +21,31 @@ public void ExecuteOnlyDerivedClassDataRowsWhenBothBaseAndDerviedClassHasDataRow
                 "DataRowTestMethod (BaseString2)",
                 "DataRowTestMethod (BaseString3)",
                 "DataRowTestMethod (DerivedString1)",
-                "DataRowTestMethod (DerivedString2)");
+                "DataRowTestMethod (DerivedString2)",
```
Comment (jayaranigarg) [inline test/E2ETests/Smoke.E2E.Tests/DataRowTests.cs]: This check has become quite long. It would be more readable if we have seperate E2E tests for `DataRowTestMethodWithSomeOptionalParameters` and `DataRowTestMethodWithAllOptionalParameters`

File: test/E2ETests/TestAssets/DataRowTestProject/BaseClass.cs [hunk 5]
```diff
@@ -16,5 +16,26 @@ public virtual void DataRowTestMethod(string a)
         {
             Assert.IsTrue(true);
         }
+
+        [TestMethod]
+        [DataRow(42)]
+        [DataRow(42, "BaseOptionalString1")]
+        [DataRow(42, "BaseOptionalString2", "BaseOptionalString3")]
+        [DataRow(42, "BaseOptionalString4", "BaseOptionalString5")]
+        public virtual void DataRowTestMethodWithSomeOptionalParameters(int i, string s1 = null, string s2 = null)
```
Comment (jayaranigarg) [inline test/E2ETests/TestAssets/DataRowTestProject/BaseClass.cs]: Please add negative test cases as well, something where user specifies less than required arguments or more than required arguments and as a result of which the test method fails with appropriate exception.

**Comment by jayaranigarg** [comment]
@ssa3512 : Thank you for your contribution!! 
PR looks good overall. Kindly do the needful changes so that we can push this in.

**Comment by jayaranigarg** [comment]
@ssa3512 : It would be even more wonderful if you can address this related issue https://github.com/Microsoft/testfx/issues/283 as well as part of this change.

**Comment by jayaranigarg** [comment]
@ssa3512 : Any updates on this? Let us know if you need some help on this.

**Comment by ssa3512** [comment]
@jayaranigarg sorry, no updates yet. I'm hoping to have some time to address the feedback and look at including #283 early next week.

**Comment by ssa3512** [comment]
@jayaranigarg I believe I addressed all feedback; should now resolve #283 as well. Please review again and let me know if anything else needs to be addressed.

File: test/E2ETests/TestAssets/DataRowTestProject/BaseClass.cs (hunk 5 above)
Comment (ssa3512) [reply test/E2ETests/TestAssets/DataRowTestProject/BaseClass.cs]: added with DataRowOptionalInvalidArguments

File: src/Adapter/MSTest.CoreAdapter/Execution/TestMethodInfo.cs (hunk 3 above)
Comment (ssa3512) [reply src/Adapter/MSTest.CoreAdapter/Execution/TestMethodInfo.cs:184]: added tests in TestMethodInfoTests.cs

File: src/Adapter/MSTest.CoreAdapter/Execution/TestMethodInfo.cs (hunk 1 above)
Comment (ssa3512) [reply src/Adapter/MSTest.CoreAdapter/Execution/TestMethodInfo.cs]: moved null check to SetArguments()

File: src/Adapter/MSTest.CoreAdapter/Execution/TestMethodInfo.cs (hunk 2 above)
Comment (ssa3512) [reply src/Adapter/MSTest.CoreAdapter/Execution/TestMethodInfo.cs]: added comments in https://github.com/Microsoft/testfx/pull/604/commits/65cd652b25348974bc42a8e3ae57416af708f23c

**Comment by ssa3512** [comment]
had to rebase - some commits were made with incorrect user id (work email)

File: src/Adapter/MSTest.CoreAdapter/Execution/TestMethodInfo.cs [hunk 6]
```diff
@@ -171,7 +171,94 @@ public virtual TestResult Invoke(object[] arguments)
...
+            // and it doesn't have a params paramenter don't try and resolve anything
+            if (requiredParameterCount == parameterInfos.Length ||
+                arguments.Length < requiredParameterCount ||
+                (!hasParamsValue && arguments.Length > parameterInfos.Length))
+            {
+                return arguments;
+            }
+
+            object[] newParameters = new object[parameterInfos.Length];
+            for (int i = 0; i < arguments.Length; i++)
```
Comment (jayaranigarg) [inline src/Adapter/MSTest.CoreAdapter/Execution/TestMethodInfo.cs]: Suggestion : Please see if we can give better name to the loop variables, that increases readability.

File: test/E2ETests/Smoke.E2E.Tests/DataRowTests.cs [hunk 7]
```diff
@@ -23,22 +23,156 @@ public void ExecuteOnlyDerivedClassDataRowsWhenBothBaseAndDerviedClassHasDataRow
...
                 "DataRowTestMethod (DerivedString1)",
                 "DataRowTestMethod (DerivedString2)");
 
-            // 3 tests of DerivedClass - 2 datarow result and 1 parent result
+            // 3 tests of DerivedClass.DataRowTestMethod - 2 datarow result and 1 parent result
+            this.ValidatePassedTestsCount(3);
+        }
+
+        [TestMethod]
+        public void ExecuteOnlyDerivedClassDataRowsWhenBothBaseAndDerviedClassHasDataRows_DataRowSomeOptional()
```
Comment (jayaranigarg) [inline test/E2ETests/Smoke.E2E.Tests/DataRowTests.cs]: We don't need to test this logic for both base and derived class. Derived class overrides base class tests is being already taken care by `ExecuteOnlyDerivedClassDataRowsWhenItOverridesBaseClassDataRows_SimpleDataRows`. 

For the tests in this PR, we should keep it simple and be focused on testing changes related to this PR i.e. have DataRowTestMethodWithSomeOptionalParameters , DataRowTestMethodWithAllOptionalParameters  and DataRowTestMethodWithParamsParameters test methods in just one class (base or derived, anyone will work). So basically 8 newly added tests in this file can be reduced to 4 and name them according to the scenario they are testing.

File: src/Adapter/MSTest.CoreAdapter/Execution/TestMethodInfo.cs (hunk 6 above)
Comment (ssa3512) [reply src/Adapter/MSTest.CoreAdapter/Execution/TestMethodInfo.cs]: resolved with https://github.com/Microsoft/testfx/pull/604/commits/30b76e08df4679a8fcda4ba7bf90ba247aacf5f9

File: test/E2ETests/Smoke.E2E.Tests/DataRowTests.cs (hunk 7 above)
Comment (ssa3512) [reply test/E2ETests/Smoke.E2E.Tests/DataRowTests.cs]: Resolved with https://github.com/Microsoft/testfx/pull/604/commits/30b76e08df4679a8fcda4ba7bf90ba247aacf5f9

File: test/E2ETests/Smoke.E2E.Tests/DataRowTests.cs [hunk 8]
```diff
@@ -23,23 +23,102 @@ public void ExecuteOnlyDerivedClassDataRowsWhenBothBaseAndDerviedClassHasDataRow
...
+                "DataRowTestMethodWithSomeOptionalParameters (42)",
+                "DataRowTestMethodWithSomeOptionalParameters (42,BaseOptionalString1)",
+                "DataRowTestMethodWithSomeOptionalParameters (42,BaseOptionalString2,BaseOptionalString3)",
+                "DataRowTestMethodWithSomeOptionalParameters (42,BaseOptionalString4,BaseOptionalString5)",
+                "DataRowTestMethodWithSomeOptionalParameters (123)",
+                "DataRowTestMethodWithSomeOptionalParameters (123,DerivedOptionalString1)",
+                "DataRowTestMethodWithSomeOptionalParameters (123,DerivedOptionalString2,DerivedOptionalString3)");
+
+            // 5 tests of BaseClass.DataRowTestMethodWithSomeOptionalParameters - 4 datarow result and 1 parent result
+            // 4 tests of DerivedClass.DataRowTestMethodWithSomeOptionalParameters - 3 datarow result and 1 parent result
```
Comment (jayaranigarg) [inline test/E2ETests/Smoke.E2E.Tests/DataRowTests.cs:55]: @ssa3512 : We can simply these tests even more by just keeping the `DataRowTestMethodWithSomeOptionalParameters` in the **dervied** class only.

File: test/E2ETests/Smoke.E2E.Tests/DataRowTests.cs [hunk 9]
```diff
@@ -23,23 +23,102 @@ public void ExecuteOnlyDerivedClassDataRowsWhenBothBaseAndDerviedClassHasDataRow
...
+        {
+            this.InvokeVsTestForExecution(new string[] { TestAssembly }, testCaseFilter: "TestCategory~DataRowAllOptional");
+
+            this.ValidatePassedTestsContain(
+                "DataRowTestMethodWithAllOptionalParameters ()",
+                "DataRowTestMethodWithAllOptionalParameters (42)",
+                "DataRowTestMethodWithAllOptionalParameters (42,BaseOptionalString6)",
+                "DataRowTestMethodWithAllOptionalParameters (42,BaseOptionalString7,BaseOptionalString8)",
+                "DataRowTestMethodWithAllOptionalParameters (42,BaseOptionalString9,BaseOptionalString10)",
+                "DataRowTestMethodWithAllOptionalParameters (123)",
```
Comment (jayaranigarg) [inline test/E2ETests/Smoke.E2E.Tests/DataRowTests.cs:66]: Similar here. We can keep `DataRowTestMethodWithAllOptionalParameters` in **derived** class only and remove from **base** class.

File: test/E2ETests/Smoke.E2E.Tests/DataRowTests.cs [hunk 10]
```diff
@@ -23,23 +23,102 @@ public void ExecuteOnlyDerivedClassDataRowsWhenBothBaseAndDerviedClassHasDataRow
...
+        public void DataRowsExecuteWithParamsArrayParameter()
+        {
+            this.InvokeVsTestForExecution(new string[] { TestAssembly }, testCaseFilter: "TestCategory~DataRowParamsArgument");
+
+            this.ValidatePassedTestsContain(
+                "DataRowTestMethodWithParamsParameters (1)",
+                "DataRowTestMethodWithParamsParameters (1,BaseSingleParamsArg)",
+                "DataRowTestMethodWithParamsParameters (1,BaseParamsArg1,BaseParamsArg2)",
+                "DataRowTestMethodWithParamsParameters (1,BaseParamsArg1,BaseParamsArg2,BaseParamsArg3)",
+                "DataRowTestMethodWithParamsParameters (2)",
```
Comment (jayaranigarg) [inline test/E2ETests/Smoke.E2E.Tests/DataRowTests.cs]: Same

File: test/E2ETests/TestAssets/DataRowTestProject/DerivedClass.cs [hunk 11]
```diff
@@ -8,12 +8,53 @@ namespace DataRowTestProject
...
+        [TestCategory("DataRowSimple")]
         [TestMethod]
         [DataRow("DerivedString1")]
         [DataRow("DerivedString2")]
         public override void DataRowTestMethod(string a)
         {
             Assert.IsTrue(true);
         }
+
+        [TestCategory("DataRowSomeOptional")]
```
Comment (jayaranigarg) [inline test/E2ETests/TestAssets/DataRowTestProject/DerivedClass.cs]: We can remove these testmethods from derived class.

File: test/E2ETests/Smoke.E2E.Tests/DataRowTests.cs [hunk 12]
```diff
@@ -23,23 +23,102 @@ public void ExecuteOnlyDerivedClassDataRowsWhenBothBaseAndDerviedClassHasDataRow
...
+        [TestMethod]
+        public void DataRowsFailWhenInvalidArgumentsProvided()
+        {
+            this.InvokeVsTestForExecution(new string[] { TestAssembly }, testCaseFilter: "TestCategory~DataRowOptionalInvalidArguments");
+
+            this.ValidatePassedTestsContain(
+                "DataRowTestMethodFailsWithInvalidArguments ()",
+                "DataRowTestMethodFailsWithInvalidArguments (1)",
+                "DataRowTestMethodFailsWithInvalidArguments (1,BaseRequiredArgument,BaseOptionalArgument,BaseExtraArgument)",
+                "DataRowTestMethodFailsWithInvalidArguments (2)",
```
Comment (jayaranigarg) [inline test/E2ETests/Smoke.E2E.Tests/DataRowTests.cs]: Here as well.

**Comment by ssa3512** [comment]
@jayaranigarg if we remove the overridden tests from DerivedClass, the E2E tests run the base class tests twice - once for BaseClass and once for DerivedClass, causing the counts of passed tests to be doubled. Is it okay to specify `FullyQualifiedName~BaseClass` in the testCaseFilter for the new E2E tests to prevent this, causing only the base class to run, or should I break the new tests out into a separate DataRowTest class that does not have a derived class?

**Comment by jayaranigarg** [comment]
> @jayaranigarg if we remove the overridden tests from DerivedClass, the E2E tests run the base class tests twice - once for BaseClass and once for DerivedClass, causing the counts of passed tests to be doubled. Is it okay to specify `FullyQualifiedName~BaseClass` in the testCaseFilter for the new E2E tests to prevent this, causing only the base class to run, or should I break the new tests out into a separate DataRowTest class that does not have a derived class?

@ssa3512 : Oh I see. I believe if we just keep these tests in the derived class, then they should not be executed twice.

**Comment by ssa3512** [comment]
> @ssa3512 : Oh I see. I believe if we just keep these tests in the derived class, then they should not be executed twice.

@jayaranigarg In that case is everything good to go?

File: test/E2ETests/TestAssets/DataRowTestProject/BaseClass.cs [hunk 13]
```diff
@@ -16,5 +17,50 @@ public virtual void DataRowTestMethod(string a)
...
+        }
+
+        [TestCategory("DataRowAllOptional")]
+        [TestMethod]
+        [DataRow()]
+        [DataRow(42)]
+        [DataRow(42, "BaseOptionalString6")]
+        [DataRow(42, "BaseOptionalString7", "BaseOptionalString8")]
+        [DataRow(42, "BaseOptionalString9", "BaseOptionalString10")]
+        public virtual void DataRowTestMethodWithAllOptionalParameters(int i = 0, string s1 = null, string s2 = null)
```
Comment (jayaranigarg) [inline test/E2ETests/TestAssets/DataRowTestProject/BaseClass.cs]: We can remove these test from the **base** class

**Comment by jayaranigarg** [comment]
@ssa3512 : I have updated my comments. You can remove the tests from the base class and have them in derived class only. It will be good to go after that.

**Comment by ssa3512** [comment]
@jayaranigarg removed tests from base class and added the `[DataRow()]` tests that were only in base to Derived

**Comment by jayaranigarg** [comment]
@ssa3512 : Looks nice🎉 I will go ahead and push this in. Thank you for the contributions 🥇

**Comment by jnyrup** [comment]
@jayaranigarg Should #283 be closed as well?

**Comment by jayaranigarg** [comment]
@jnyrup: Yes. This PR adds support for params as well. Updated the title to be more explicit.

**Comment by julealgon** [comment]
`params` support is completely unrelated to supporting default parameter values.

I'd suggest updating the release notes to make it clear that `params` is also supported on 2.0.0 now. The current release notes doesn't mention it at all, I assume because it only keeps track of issues, and we didn't have an issue to track this part of the work here:

image

In the future, I'd suggest being mindful of these changes and:
1. Sending them in separate PRs to promote isolation of changes
2. Ensuring that all functional changes are covered by an issue item for tracking
