### PR TITLE
Fix class initialization/cleanup calls

### LINKED ISSUE #1889: ClassCleanup not called in base class
## Describe the bug

MSTest.TestFramework 3.0.4

ClassCleanup method in base class not called

    [TestClass]
    public class BaseClass
    {
        [ClassCleanup]
        public static void ClassCleanupBase()
        {
            Console.WriteLine(nameof(BaseClass) + nameof(ClassCleanupBase));
        }
    }

    [TestClass]
    public class UnitTest1 : BaseClass
    {
        [TestMethod]
        public void TestMethod1()
        {
            Console.WriteLine(nameof(TestMethod1));
        }
    /*
        [ClassCleanup]
        public static void ClassCleanup()
        {
            Console.WriteLine(nameof(UnitTest1) + nameof(ClassCleanup));
        }
    */
    }

## Additional context

Verified in debuger.
Also mentioned in [Class Initialize inheritance #143](https://github.com/microsoft/testfx/issues/143#issuecomment-747357059)
The commented method works.

### PR DESCRIPTION
**Pull request by Evangelink**
Fixes #1889

### CODE REVIEW

File: src/Adapter/MSTest.TestAdapter/Execution/TestClassInfo.cs [hunk 1]
```diff
@@ -144,7 +135,12 @@ internal set
     /// <summary>
     /// Gets a stack of class cleanup methods to be executed.
     /// </summary>
-    public Stack<MethodInfo> BaseClassCleanupMethodsStack { get; internal set; }
+    [Obsolete("API will be dropped in v4")]
```
Comment (fhnaseer) [inline src/Adapter/MSTest.TestAdapter/Execution/TestClassInfo.cs:138]: Should we mention alternative (BaseClassCleanupMethods) here? Same comment for all other obsolete attributes as well.

**Review by fhnaseer — APPROVED** [review]

File: src/Adapter/MSTest.TestAdapter/Execution/TestClassInfo.cs (hunk 1 above)
Comment (Evangelink) [reply src/Adapter/MSTest.TestAdapter/Execution/TestClassInfo.cs:138]: Good remark! The replacement is internal but there is no good reason to have the class public so I'll keep as-is as users have no alternative.
