### PR TITLE
Remove ClassCleanupBehavior

### LINKED ISSUE #1316: Change ClassCleanup default behavior to be "EndOfClass"
## Summary

Current behavior of `ClassCleanupAttribute` is to be run at the end of the assembly and not at the end of the class as the name would suggest. 

Note that it is possible to change this behavior (locally with a ctor/property) or globally using `ClassCleanupExecutionAttribute`.

## Proposed Enhancement

Change default behavior to be `EndOfClass`. Although this is a breaking change, it will be possible for users to revert to old behavior simply by adding `[assembly: ClassCleanupExecution(ClassCleanupBehavior.EndOfAssembly)]`.

[AB#1711729](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1711729)

### LINKED ISSUE #1574: Remove `ClassCleanupBehavior.EndOfAssembly`
## Summary

The initial idea was to deprecate `ClassCleanupBehavior.EndOfAssembly` and remove it in a later release (see #1541) but given that we already did the breaking change of replacing default from `EndOfAssembly` to `EndOfClass` (see #1316), it seems that people who would be broken would already have to do fix their tests so we could directly guide them toward using `AssemblyCleanup`.

[AB#1736146](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1736146)

### PR DESCRIPTION
**Pull request by Youssef1313**
Closes #1316
Closes #1574
Related to #1285

### CODE REVIEW

File: src/Adapter/MSTestAdapter.PlatformServices/MSTestSettings.cs [hunk 1]
```diff
@@ -485,21 +479,6 @@ private static MSTestSettings ToSettings(XmlReader reader, IMessageLogger? logge
                             break;
                         }
 
-                    case "CLASSCLEANUPLIFECYCLE":
```
Comment (Evangelink) [inline src/Adapter/MSTestAdapter.PlatformServices/MSTestSettings.cs:488]: Shall we emit a warning to let people know they can/need to cleanup their runsettings?

File: src/Adapter/MSTestAdapter.PlatformServices/MSTestSettings.cs [hunk 2]
```diff
@@ -970,20 +949,6 @@ internal static void SetSettingsFromConfig(IConfiguration configuration, IMessag
         ParseIntegerSetting(configuration, "timeout:testInitialize", logger, value => settings.TestInitializeTimeout = value);
         ParseIntegerSetting(configuration, "timeout:testCleanup", logger, value => settings.TestCleanupTimeout = value);
 
-        if (configuration["mstest:classCleanupLifecycle"] is string classCleanupLifecycle)
```
Comment (Evangelink) [inline src/Adapter/MSTestAdapter.PlatformServices/MSTestSettings.cs:973]: Shall we emit a warning to let people know they can/need to cleanup their json?

**Comment by Youssef1313** [comment]
> I think we can drop analyzer + codefix related to that

@Evangelink it's already dropped, unless there is something I'm missing

File: src/Adapter/MSTestAdapter.PlatformServices/MSTestSettings.cs (hunk 1 above)
Comment (Youssef1313) [reply src/Adapter/MSTestAdapter.PlatformServices/MSTestSettings.cs:488]: Sure

File: src/Analyzers/MSTest.Analyzers/UseClassCleanupBehaviorEndOfClassAnalyzer.cs [hunk 3]
```diff
@@ -1,110 +0,0 @@
...
-/// </summary>
-[DiagnosticAnalyzer(LanguageNames.CSharp, LanguageNames.VisualBasic)]
-public sealed class UseClassCleanupBehaviorEndOfClassAnalyzer : DiagnosticAnalyzer
-{
-    private static readonly LocalizableResourceString Title = new(nameof(Resources.UseClassCleanupBehaviorEndOfClassTitle), Resources.ResourceManager, typeof(Resources));
-    private static readonly LocalizableResourceString Description = new(nameof(Resources.UseClassCleanupBehaviorEndOfClassDescription), Resources.ResourceManager, typeof(Resources));
-    private static readonly LocalizableResourceString MessageFormat = new(nameof(Resources.UseClassCleanupBehaviorEndOfClassMessageFormat), Resources.ResourceManager, typeof(Resources));
-
-    internal static readonly DiagnosticDescriptor UseClassCleanupBehaviorEndOfClassRule = DiagnosticDescriptorHelper.Create(
-        id: DiagnosticIds.UseClassCleanupBehaviorEndOfClassRuleId,
```
Comment (Evangelink) [inline src/Analyzers/MSTest.Analyzers/UseClassCleanupBehaviorEndOfClassAnalyzer.cs:26]: Deprecate this diagnostic ID as you did on the other PR please.

**Review by Evangelink — APPROVED** [review]

**Comment by Youssef1313** [comment]
@mariam-abdulla Can you please look into `ValidateTestRunLifecycle` test (and related test assets) to adjust for the breaking change here?

For context, `ClassCleanupBehavior.EndOfAssembly` was previously the default. With this PR, `EndOfAssembly` is removed completely, and we only have `EndOfClass` now.

File: src/Adapter/MSTestAdapter.PlatformServices/MSTestSettings.cs (hunk 1 above)
Comment (Evangelink) [reply src/Adapter/MSTestAdapter.PlatformServices/MSTestSettings.cs:488]: Closing here, let's do as a follow-up.
