### PR TITLE
Ensure code fixers are handling indentation/newlines correctly

### LINKED ISSUE #7204: MSTEST0037 code fix messes up whitespace / new lines
## Describe the bug

I've been tasked to upgrade multiple of our projects from `MsTest 3.x` to `4.x`. In doing so, i upgrade Package Version in steps, ie: 3.9.* -> 3.10.* -> 3.11 [-> 4.* where applicable].
The new Analyzers/CodeFixes are not implemented with enough care. A "fix all in solution" results in widespread ugly code.

## Steps To Reproduce

1. include a version with Analyzer+Codefix for MSTEST0037
2. 
```cs
[TestClass]
public sealed class Test1
{
    [TestMethod]
    public void TestMethod1()
    {
        List<int> numbers = [1, 2, 3];
        Assert.IsTrue(numbers.Contains(2),
          "list has wrong count");
    }
}
```

## Expected behavior
```cs
namespace TestProject1;

[TestClass]
public sealed class Test1
{
    [TestMethod]
    public void TestMethod1()
    {
        List<int> numbers = [1, 2, 3];
        Assert.Contains(2, numbers,
          "list has wrong count");
    }
}

```
## Actual behavior

Image

```cs
[TestClass]
public sealed class Test1
{
    [TestMethod]
    public void TestMethod1()
    {
        List<int> numbers = [1, 2, 3];
        Assert.Contains(2,
numbers, "list has wrong count");
    }
}

```
## Additional context
this bugfix should be backported to 3.x to ease migration

### PR DESCRIPTION
**Pull request by Evangelink**
Fixes #7204

### CODE REVIEW

File: src/Analyzers/MSTest.Analyzers.CodeFixes/UseProperAssertMethodsFixer.cs [hunk 1]
```diff
@@ -163,9 +168,47 @@ private static async Task<Document> FixAssertMethodForAddArgumentModeAsync(Docum
             ExpressionSyntax expression => expression,
             _ => throw new InvalidOperationException($"Unexpected node type for expected argument: {expectedNode.GetType()}"),
         };
-        newArgumentList = newArgumentList.ReplaceNode(conditionNode, SyntaxFactory.Argument(expectedExpression).WithAdditionalAnnotations(Formatter.Annotation));
-        int insertionIndex = argumentList.Arguments.IndexOf(conditionNode) + 1;
-        newArgumentList = newArgumentList.WithArguments(newArgumentList.Arguments.Insert(insertionIndex, SyntaxFactory.Argument(actualNode).WithAdditionalAnnotations(Formatter.Annotation)));
+
+        // Preserve the leading trivia from the original condition argument, remove trailing trivia
```
Comment (Youssef1313) [inline src/Analyzers/MSTest.Analyzers.CodeFixes/UseProperAssertMethodsFixer.cs:172]: Not super happy with how complex this fixer (and the corresponding analyzer) are getting.

Approving given the tests, but I would like to be able to simplify the fixer overall (not trivia handling specifically)

Comment (Evangelink) [reply src/Analyzers/MSTest.Analyzers.CodeFixes/UseProperAssertMethodsFixer.cs:172]: I'll try to give it a go, see if I can find ways to simplify the analyzer.

Comment (Evangelink) [reply src/Analyzers/MSTest.Analyzers.CodeFixes/UseProperAssertMethodsFixer.cs:172]: I'll try to give it a go, see if I can find ways to simplify the analyzer.
