### PR TITLE
Fix diff marker in Assert.AreEqual when strings are compared to not point at '...'

### LINKED ISSUE #6784: Visual indicator for string AreEqual doesn't work well for mismatches at the end of long strings
## Summary
Good dehavior with enough characters at the end
```
Assert.AreEqual("01234567890123456789012345678901234567890123X", "01234567890123456789012345678901234567890123456789");

Assert.AreEqual failed. Expected string length 45 but was 50. 'expected' expression: '"01234567890123456789012345678901234567890123X"', 'actual' expression: '"01234567890123456789012345678901234567890123456789"'.
Expected: "...23456789012345678901234567890123X"
But was:  "...23456789012345678901234567890123456789"
----------------------------------------------^
```

Bad behavior with not enough characters at the end
```
Assert.AreEqual("01234567890123456789012345678901234567890123X", "01234567890123456789012345678901234567890123456");

 Assert.AreEqual failed. Expected string length 45 but was 47. 'expected' expression: '"01234567890123456789012345678901234567890123X"', 'actual' expression: '"01234567890123456789012345678901234567890123456"'.
 Expected: "...7890123456789012345678901234567890123X"
 But was:  "...78901234567890123456789012345678901..."
 ---------------------------------------------------^
```
## Background and Motivation

While verifying new behavior for mismatches I noticed that I wasn't able to see the mismatch at the end of a long string.

## Proposed Feature

Similar to how when there are 5 characters after the mismatch and the end of the longer string is shown it should not produce ellipsis to hide the mismatch for only 2 additional characters.

### PR DESCRIPTION
**Pull request by nohwnd**
Fix #6784

### CODE REVIEW

File: test/UnitTests/TestFramework.UnitTests/Assertions/AssertTests.AreEqualTests.cs [hunk 1]
```diff
@@ -1628,4 +1707,19 @@ private static string DigitString(int length, int diffIndex)
 
         return result.ToString();
     }
+
+    private void StringPreviewsAreEqual(string expected, string actual)
```
Comment (nohwnd) [inline test/UnitTests/TestFramework.UnitTests/Assertions/AssertTests.AreEqualTests.cs:1711]: awesome assertions shorten the text and replace new lines, that makes it much harder to see the diff. This just shows it as is.

File: test/UnitTests/TestFramework.UnitTests/Assertions/AssertTests.AreEqualTests.cs [hunk 2]
```diff
@@ -1537,11 +1539,12 @@ public void CreateStringPreviews_DiffPointsToCorrectPlaceInShortenedStringWithEn
         int length = preview + 10;
         int diffIndex = 0;
         string stringPreview = FormatStringPreview(StringPreviewHelper.CreateStringPreviews(DigitString(length, diffIndex), DigitString(length, diffIndex), diffIndex, preview));
-        stringPreview.Should().Be("""
+        StringPreviewsAreEqual(
+            """
             "X12345..."
```
Comment (Youssef1313) [inline test/UnitTests/TestFramework.UnitTests/Assertions/AssertTests.AreEqualTests.cs:1544]: Not sure if this should be a single ellipsis char `…` instead of three dots `...`, but that's a different topic.

Comment (nohwnd) [reply test/UnitTests/TestFramework.UnitTests/Assertions/AssertTests.AreEqualTests.cs:1544]: Single ellipsis might not render everywhere.
