### PR TITLE
Fail on warn as error in discovery

### LINKED ISSUE #5992: `TreatDiscoveryWarningsAsErrors` should throw instead of sending message
https://github.com/microsoft/testfx/blob/96f6b1cc6138cd5a3166355b54547bae6df0c2b4/src/Adapter/MSTestAdapter.PlatformServices/Discovery/UnitTestDiscoverer.cs#L71

To guarantee that the error will end up failing the test run, we should throw an exception.

### PR DESCRIPTION
**Pull request by Evangelink**
Replaces #6202 and fixes #5992

### CODE REVIEW

File: src/TestFramework/TestFramework/Exceptions/MSTestException.cs [hunk 1]
```diff
@@ -0,0 +1,57 @@
...
+using System.ComponentModel;
+using System.Runtime.Serialization;
+
+namespace Microsoft.VisualStudio.TestTools.UnitTesting;
+
+/// <summary>
+/// Base class for Framework Exceptions.
+/// </summary>
+[Serializable]
+public class MSTestException : Exception
```
Comment (Youssef1313) [inline src/TestFramework/TestFramework/Exceptions/MSTestException.cs:13]: Intentionally public?

**Review by Youssef1313 — APPROVED** [review]

File: src/TestFramework/TestFramework/Exceptions/MSTestException.cs (hunk 1 above)
Comment (Evangelink) [reply src/TestFramework/TestFramework/Exceptions/MSTestException.cs:13]: Yes I want to reuse this for an open issue we have
