### PR TITLE
Flow assert expected and actual to be printed on CLI or TE

### LINKED ISSUE #6717: Assert.AreEqual string: consider displaying the full actual and expected in addition to the diff
## Summary

Let's take the following error diff:

```
Assert.AreEqual failed. Expected string length 199 but was 139. 'expected' expression: 'Normalize(expected)', 'actual' expression: 'Normalize(actual)'.
Expected: "...n 1; }␊    #endregion␊␊    #region ..."
But was:  "...n 1; }␊    #endregion␊    #endregion␊}"
```

This is nice for spotting the exact difference but it's sometimes interesting to have access to the full context.

For examples:

1. When you are in a scenario where you are changing the output, it's useful to be able to copy the new expected content to replace current expected.

2. When there are more than one issue, you would need to run the assert multiple times when having the full actual/expected might allow you to do an extra check upfront.

### PR DESCRIPTION
**Pull request by Evangelink**
Fix #6717

### CODE REVIEW

File: src/TestFramework/TestFramework/Assertions/Assert.cs [hunk 1]
```diff
@@ -40,6 +40,70 @@ internal static void ThrowAssertFailed(string assertionName, string? message)
...
+
+        if (HasKnownGoodToString(actual))
+        {
+            exception.Data["assert.actual"] = actual;
+        }
+
+        throw exception;
+    }
+
+    private static bool HasKnownGoodToString([NotNullWhen(true)] object? value)
```
Comment (Evangelink) [inline src/TestFramework/TestFramework/Assertions/Assert.cs:82]: We could improve the logic to try to detect if the given type overrides `ToString` in which case we call it. We could also allow users to register a method for the display representation of types. 

But all of that can happen later, we are already improving experience as-is.

File: samples/Playground/Tests.cs [hunk 2]
```diff
@@ -15,5 +15,9 @@ public class TestClass
     [TestMethod]
     public void Test1()
     {
+        string commonPart = new('a', 1000);
+        string expected = commonPart + "expected";
+        string actual = commonPart + "actual";
+        Assert.AreEqual(expected, actual, ignoreCase: true);
```
Comment (Evangelink) [inline samples/Playground/Tests.cs]:
```suggestion
        // string commonPart = new('a', 1000);
        // string expected = commonPart + "expected";
        // string actual = commonPart + "actual";
        // Assert.AreEqual(expected, actual, ignoreCase: true);
```
