### PR TITLE
Drop stacktrace trimming

### LINKED ISSUE #4266: Revise Regex usage in TrimStackTrace
https://github.com/microsoft/testfx/blob/beb890d4fe699cf718748884c1e642e28239c1fc/src/Adapter/MSTest.TestAdapter/Execution/ExceptionHelper.cs#L109

It doesn't make much sense to me to use Regex here.

Not so much allocations but would be good to reduce:

Image

### PR DESCRIPTION
**Pull request by Evangelink**
Fix #4266

### CODE REVIEW

File: src/Adapter/MSTestAdapter.PlatformServices/Extensions/ExceptionExtensions.cs [hunk 1]
```diff
@@ -1,6 +1,8 @@
 ﻿// Copyright (c) Microsoft Corporation. All rights reserved.
 // Licensed under the MIT license. See LICENSE file in the project root for full license information.
 
+using System.Diagnostics;
```
Comment (Evangelink) [inline src/Adapter/MSTestAdapter.PlatformServices/Extensions/ExceptionExtensions.cs]:
```suggestion
```

File: test/IntegrationTests/MSTest.Acceptance.IntegrationTests/GenericTestMethodTests.cs [hunk 2]
```diff
@@ -20,58 +20,62 @@ public async Task TestDifferentGenericMethodTestCases()
...
-              Cannot create an instance of T\[] because Type\.ContainsGenericParameters is true\.
-                .+?
-            failed ParameterizedMethodWithNestedGeneric \(System\.Collections\.Generic\.List`1\[System.String],System\.Collections\.Generic\.List`1\[System.String]\) \(\d+ms\)
-              Assert\.Fail failed\. Test method 'ParameterizedMethodWithNestedGeneric' did run with first list \[Hello, World] and second list \[Unit, Testing]
-                .+?
-            failed ParameterizedMethodWithNestedGeneric \(System\.Collections\.Generic\.List`1\[System.Int32],System\.Collections\.Generic\.List`1\[System.Int32]\) \(\d+ms\)
-              Assert\.Fail failed\. Test method 'ParameterizedMethodWithNestedGeneric' did run with first list \[0, 1] and second list \[2, 3]
-                .+?
-            """, RegexOptions.Singleline);
+failed AMethodWithBadConstraints \(0\) \((?:\d+s\s?)?(?:\d+ms)\)
```
Comment (Youssef1313) [inline test/IntegrationTests/MSTest.Acceptance.IntegrationTests/GenericTestMethodTests.cs]: I personally prefer the old indentation

**Review by Youssef1313 — APPROVED** [review]

File: test/IntegrationTests/MSTest.Acceptance.IntegrationTests/GenericTestMethodTests.cs (hunk 2 above)
Comment (Evangelink) [reply test/IntegrationTests/MSTest.Acceptance.IntegrationTests/GenericTestMethodTests.cs]: Moving to the left was helping me to diff where things got wrong, we were losing too much screen space. I can reset now if you prefer.

File: test/IntegrationTests/MSTest.Acceptance.IntegrationTests/GenericTestMethodTests.cs [hunk 3]
```diff
@@ -20,57 +20,61 @@ public async Task TestDifferentGenericMethodTestCases()
         testHostResult.AssertExitCodeIs(ExitCodes.AtLeastOneTestFailed);
         testHostResult.AssertOutputMatchesRegex(
             """
-            failed AMethodWithBadConstraints \(0\) \((\d+s )?\d+ms\)
+            failed AMethodWithBadConstraints \(0\) \((?:\d+s\s?)?(?:\d+ms)\)
```
Comment (Youssef1313) [inline test/IntegrationTests/MSTest.Acceptance.IntegrationTests/GenericTestMethodTests.cs]: Isn't the previous regex more readable? The part of an optional "seconds" component of duration is already fixed. So I guess the changes here are unnecessary.

File: test/IntegrationTests/MSTest.Acceptance.IntegrationTests/GenericTestMethodTests.cs [hunk 4]
```diff
@@ -20,57 +20,61 @@ public async Task TestDifferentGenericMethodTestCases()
...
               GenericArguments\[0], 'System\.Int32', on 'Void AMethodWithBadConstraints\[T]\(T\)' violates the constraint of type 'T'\.
-                .+?
-            failed NonParameterizedTestMethod \((\d+s )?\d+ms\)
+            .+?
```
Comment (Youssef1313) [inline test/IntegrationTests/MSTest.Acceptance.IntegrationTests/GenericTestMethodTests.cs]: There are spaces removed here.

Comment (Evangelink) [reply test/IntegrationTests/MSTest.Acceptance.IntegrationTests/GenericTestMethodTests.cs]: Yes it was causing problems with multi-lines stack traces

File: test/IntegrationTests/MSTest.Acceptance.IntegrationTests/GenericTestMethodTests.cs (hunk 3 above)
Comment (Evangelink) [reply test/IntegrationTests/MSTest.Acceptance.IntegrationTests/GenericTestMethodTests.cs]: Fine by me, reverting this part. Note that it was done before you fixed something (PR is open for a bit now)

File: test/IntegrationTests/MSTest.Acceptance.IntegrationTests/GenericTestMethodTests.cs (hunk 4 above)
Comment (Youssef1313) [reply test/IntegrationTests/MSTest.Acceptance.IntegrationTests/GenericTestMethodTests.cs]: How so? We use RegexOptions.SingleLine here which means the `.` will match new lines. The removed whitespaces here was asserting that at least the start of the stack trace is indented correctly.

If it's failing now, that means there is a change in behavior in stack trace indentation, which would be a bug.

Comment (Evangelink) [reply test/IntegrationTests/MSTest.Acceptance.IntegrationTests/GenericTestMethodTests.cs]: Let me undo and see on CI. Pretty sure there was some indeterminism in the stacktrace shown

File: test/IntegrationTests/MSTest.Acceptance.IntegrationTests/GenericTestMethodTests.cs [hunk 5]
```diff
@@ -36,20 +36,24 @@ public async Task TestDifferentGenericMethodTestCases()
               Assert\.Fail failed\. Test method 'ParameterizedMethodSimple' did run with parameter 'Hello world' and type 'System\.String'\.
                 .+?
             failed ParameterizedMethodSimple \(null\) \((\d+s )?\d+ms\)
-              Test method TestClass\.ParameterizedMethodSimple threw exception: 
+              Test method TestClass\.ParameterizedMethodSimple threw exception:
```
Comment (Youssef1313) [inline test/IntegrationTests/MSTest.Acceptance.IntegrationTests/GenericTestMethodTests.cs:39]: There is an extra whitespace here at the end (that I wasn't aware it exists!) and it's removed now. It originates from here:

https://github.com/microsoft/testfx/blob/d879f669ec5a48dddc72641b9fbcc3710a7c4061/src/Adapter/MSTestAdapter.PlatformServices/Resources/Resource.resx#L469

So I guess that might cause the test to fail now

Comment (Evangelink) [reply test/IntegrationTests/MSTest.Acceptance.IntegrationTests/GenericTestMethodTests.cs:39]: Let me fix the resx!
