### PR TITLE
Fix TypeCache to throw on duplicate attributes when necessary

### LINKED ISSUE #4333: `GetFirstDerivedAttributeOrDefault` implementation isn't consistent with doc comment
Doc says:

> /// <exception cref="InvalidOperationException">Throws when multiple attributes are found (the attribute must allow multiple).</exception>

Implementation:

```csharp
        Attribute[] cachedAttributes = GetCustomAttributesCached(attributeProvider, inherit);

        foreach (Attribute cachedAttribute in cachedAttributes)
        {
            if (AttributeComparer.IsDerived<TAttribute>(cachedAttribute))
            {
                return (TAttribute)cachedAttribute;
            }
        }

        return null;
```

My suggestion:

1. Remove the doc comment about throwing an exception and leave the method as-is
2. Introduce a new method that throws an exception and name it `GetSingleDerivedAttributeOrDefault`. Note that throwing exception may still be relevant even if AllowMultiple is not true (ONLY IF the attribute is not sealed). See https://github.com/microsoft/testfx/issues/4331 for details.
3. Revise all usages, and switch from `GetFirstDerivedAttributeOrDefault` to `GetSingleDerivedAttributeOrDefault` if needed.
4. My expectation is that after we do these three steps, we will end up having `GetFirstDerivedAttributeOrDefault` called with **sealed** attributes only. If this happened, we can switch all these to `GetFirstNonDerivedAttributeOrDefault` and delete `GetFirstDerivedAttributeOrDefault`

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #4333

### CODE REVIEW

File: src/Adapter/MSTestAdapter.PlatformServices/Helpers/ReflectHelper.cs [hunk 1]
```diff
@@ -87,6 +92,37 @@ internal class ReflectHelper : MarshalByRefObject
...
+        Attribute[] cachedAttributes = GetCustomAttributesCached(attributeProvider);
+
+        TAttribute? foundAttribute = null;
+        foreach (Attribute cachedAttribute in cachedAttributes)
+        {
+            if (cachedAttribute is TAttribute cachedAttributeAsTAttribute)
+            {
+                if (foundAttribute is not null)
+                {
+                    throw new InvalidOperationException($"Multiple attributes of type '{typeof(TAttribute)}' found.");
```
Comment (Youssef1313) [inline src/Adapter/MSTestAdapter.PlatformServices/Helpers/ReflectHelper.cs:116]: TODO: localize.

**Review by fhnaseer — APPROVED** [review]
