### PR TITLE
Error if framework/adapter versions are mismatched at runtime

### LINKED ISSUE #5653: Throw exception at runtime if TestAdapter and TestFramework versions are mismatched
I think it's generally a good idea to enforce the same TestAdapter and TestFramework versions. When there is a mismatch, the exception should include the two versions that were used.

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #5653

### CODE REVIEW

File: src/Adapter/MSTest.TestAdapter/VSTestAdapter/MSTestExecutor.cs [hunk 1]
```diff
@@ -47,6 +48,20 @@ internal MSTestExecutor(CancellationToken cancellationToken)
...
+    [ModuleInitializer]
+#pragma warning restore CA2255 // The 'ModuleInitializer' attribute should not be used in libraries
+    internal static void EnsureAdapterAndFrameworkVersions()
+    {
+        string? adapterVersion = typeof(MSTestExecutor).Assembly.GetCustomAttribute<AssemblyInformationalVersionAttribute>()?.InformationalVersion;
+        string? frameworkVersion = typeof(TestMethodAttribute).Assembly.GetCustomAttribute<AssemblyInformationalVersionAttribute>()?.InformationalVersion;
+        if (adapterVersion is not null && frameworkVersion is not null
+            && adapterVersion != frameworkVersion)
+        {
+            throw new InvalidOperationException($"MSTest.TestAdapter and MSTest.TestFramework must have the same version. Found MSTest.TestAdapter version '{adapterVersion}' and MSTest.TestFramework version {frameworkVersion}.");
```
Comment (Evangelink) [inline src/Adapter/MSTest.TestAdapter/VSTestAdapter/MSTestExecutor.cs]: Message should be localized. I would do a nit and add quotes around package names.

Comment (Youssef1313) [reply src/Adapter/MSTest.TestAdapter/VSTestAdapter/MSTestExecutor.cs]: I'll do after your PR https://github.com/microsoft/testfx/pull/5713 is merged to avoid conflicts with resx changes

Comment (Youssef1313) [reply src/Adapter/MSTest.TestAdapter/VSTestAdapter/MSTestExecutor.cs]: Fixed.

File: src/Adapter/MSTestAdapter.PlatformServices/Resources/Resource.resx [hunk 2]
```diff
@@ -484,4 +484,7 @@ Error: {1}</value>
   <data name="STAIsOnlySupportedOnWindowsWarning" xml:space="preserve">
     <value>Runsettings entry '&lt;ExecutionApartmentState&gt;STA&lt;/ExecutionApartmentState&gt;' is not supported on non-Windows OSes.</value>
   </data>
+  <data name="VersionMismatchBetweenAdapterAndFramework" xml:space="preserve">
+    <value>'MSTest.TestAdapter' and 'MSTest.TestFramework' must have the same version. Found 'MSTest.TestAdapter' version '{0}' and 'MSTest.TestFramework' version '{1}'.</value>
```
Comment (nohwnd) [inline src/Adapter/MSTestAdapter.PlatformServices/Resources/Resource.resx]: I would like the message to also tell me the most likely solution. 

```suggestion
    <value>'MSTest.TestAdapter' and 'MSTest.TestFramework' must have the same version. Found 'MSTest.TestAdapter' version '{0}' and 'MSTest.TestFramework' version '{1}'. Please make sure that the versions of  'MSTest.TestAdapter' and 'MSTest.TestFramework' NuGet packages have the same version.</value>
```

File: src/Adapter/MSTest.TestAdapter/VSTestAdapter/MSTestExecutor.cs [hunk 3]
```diff
@@ -49,6 +49,20 @@ internal MSTestExecutor(CancellationToken cancellationToken)
...
     public TestExecutionManager TestExecutionManager { get; protected set; }
 
+#pragma warning disable CA2255 // The 'ModuleInitializer' attribute should not be used in libraries
+    [ModuleInitializer]
+#pragma warning restore CA2255 // The 'ModuleInitializer' attribute should not be used in libraries
+    internal static void EnsureAdapterAndFrameworkVersions()
+    {
+        string? adapterVersion = typeof(MSTestExecutor).Assembly.GetCustomAttribute<AssemblyInformationalVersionAttribute>()?.InformationalVersion;
+        string? frameworkVersion = typeof(TestMethodAttribute).Assembly.GetCustomAttribute<AssemblyInformationalVersionAttribute>()?.InformationalVersion;
+        if (adapterVersion is not null && frameworkVersion is not null
```
Comment (nohwnd) [inline src/Adapter/MSTest.TestAdapter/VSTestAdapter/MSTestExecutor.cs:59]: when they mix 2.x.x version with 3.x.x you won't get the informational version on test framework and the message will not show up.

Comment (Youssef1313) [reply src/Adapter/MSTest.TestAdapter/VSTestAdapter/MSTestExecutor.cs:59]: Hmm, I looked with ILSpy and the `AssemblyInformationalVersion` is 14.x for packages 2.x. It makes the message a bit unclear but is it big of an issue?

Comment (nohwnd) [reply src/Adapter/MSTest.TestAdapter/VSTestAdapter/MSTestExecutor.cs:59]: Okay for me, I must have overlooked it.

**Review by nohwnd — APPROVED** [review]
